const IconImage = {
  arrowDown: require('./images/arrow-down.svg').default,
  arrowLeftShortFill: require('./images/arrow-left-short-fill.svg').default,
  arrowRightShortFill: require('./images/arrow-right-short-fill.svg').default,
  arrowUp: require('./images/arrow-up.svg').default,
  bookmarkCheckFill: require('./images/bookmark-check-fill.svg').default,
  bookmarkPlusFill: require('./images/bookmark-plus-fill.svg').default,
  calendarAllFill: require('./images/calendar-all-fill.svg').default,
  capslockFill: require('./images/capslock-fill.svg').default,
  check2: require('./images/check-2.svg').default,
  checkCircleFill: require('./images/check-circle-fill.svg').default,
  chevronCompactLeft: require('./images/chevron-compact-left.svg').default,
  chevronCompactRight: require('./images/chevron-compact-right.svg').default,
  chevronLeft2: require('./images/chevron-left-2.svg').default,
  chevronRight2: require('./images/chevron-right-2.svg').default,
  exclamationCircleFill: require('./images/exclamation-circle-fill.svg').default,
  exclamationDiamondFill: require('./images/exclamation-diamond-fill.svg').default,
  forwardFill: require('./images/forward-fill.svg').default,
  houseFill: require('./images/house-fill.svg').default,
  imageFill: require('./images/image-fill.svg').default,
  infoCircleFill: require('./images/info-circle-fill.svg').default,
  patchCheckFill: require('./images/patch-check-fill.svg').default,
  pencilFill: require('./images/pencil-fill.svg').default,
  personFill: require('./images/person-fill.svg').default,
  plusCircleFill: require('./images/plus-circle-fill.svg').default,
  plus: require('./images/plus.svg').default,
  questionCircleFill: require('./images/question-circle-fill.svg').default,
  search: require('./images/search.svg').default,
  threeDotsVertical: require('./images/three-dots-vertical.svg').default,
  threeDots: require('./images/three-dots.svg').default,
  xCircleFill: require('./images/x-circle-fill.svg').default,
  x: require('./images/x.svg').default,
  threads: require('./images/threads.svg').default,
  xTwitter: require('./images/xTwitter.svg').default,
};

export { IconImage };
